// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xzukwevimufaoceckdzq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh6dWt3ZXZpbXVmYW9jZWNrZHpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMTk4NzQsImV4cCI6MjA3MTc5NTg3NH0.o3Sxmn5UdCKgg6GhS3r2VpHc2CzhjP7iYlM9NWOI9xQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});